#!/usr/bin/env bash
# ci-walden tenant-interface v5 — generated by ci-walden tenant-init
# stack: declared (declared entry point (ci-walden/interface.json); the interface calls it and propagates its exit code)
# contract: bash at repo root; exit status is the verdict (0 = green)
# regenerating this file on an unchanged repo is a no-op diff
# conformance: sha256:472e5626cb37573b7095931321dda23819b82db78d281196ab4cf86ad23dc445
set -eo pipefail
cargo fmt --all -- --check && cargo check --workspace --all-features && cargo clippy --workspace --all-features -- -D warnings && cargo test --workspace --all-features && RUSTDOCFLAGS="--cfg docsrs -Dwarnings" cargo doc --workspace --all-features --no-deps
